import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { Source_Sans_3 } from "next/font/google";
import Providers from "./providers";
import { Toaster } from "react-hot-toast";

const sourceSans = Source_Sans_3({
  variable: "--font-source-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // jitna chahiye
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
       className={`${sourceSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col"><Providers><Header/>{children}   <Toaster position="top-right" /></Providers><Footer/></body>
    </html>
  );
}
